# The module name is part of the generated dictConfig import path.
# ruff: file-ignore[stdlib-module-shadowing]
"""Reconstruct Litestar's active formatter in Granian's logging config."""

import base64
import logging
import logging.config
import pickle  # ruff: ignore[suspicious-pickle-import]
from collections.abc import Iterable, Mapping, Sequence
from copy import deepcopy
from types import MemberDescriptorType
from typing import Any, Protocol, cast

from granian.log import LOGGING_CONFIG


class _FormatterSetupError(RuntimeError):
    """Raised when automatic formatter matching cannot cross the process boundary."""


class _LogFormatter(Protocol):
    def format(self, record: logging.LogRecord) -> str: ...


def build_logging_config(
    logging_config: object | None,
    *,
    logger: logging.Logger | None = None,
) -> dict[str, Any] | None:
    """Match Granian to Litestar's effective formatter without copying logging machinery.

    Args:
        logging_config: Litestar's logging configuration, used only as a
            structural fallback when the active logger graph has no formatter.
        logger: Logger graph entry point. Defaults to the active ``litestar``
            standard-library logger.

    Returns:
        A deep copy of Granian's native config with reconstructed formatters,
        or ``None`` when no compatible Litestar formatter exists.
    """
    selected = _formatter_from_logger(logger or logging.getLogger("litestar"))
    if selected is None:
        selected = _formatter_from_config(logging_config)
    if selected is None:
        return None

    formatter_config = _serialized_formatter(selected)
    config = cast("dict[str, Any]", deepcopy(LOGGING_CONFIG))
    formatters = cast("dict[str, Any]", config["formatters"])
    formatters["generic"] = dict(formatter_config)
    formatters["access"] = dict(formatter_config)
    return config


def load_serialized_formatter(payload: str) -> _LogFormatter:
    """Create a fresh child-owned formatter-compatible object.

    The mode-600 configuration is generated by this package from a formatter
    already selected in the Litestar parent. No handlers, queues, listeners,
    loggers, locks, levels, or other live logging state cross the boundary.

    Args:
        payload: Base64-encoded pickle generated by
            :func:`build_logging_config`.

    Returns:
        A child-owned object with a callable ``format(record)`` method.

    Raises:
        TypeError: If the reconstructed object has no callable ``format``.
    """
    formatter = pickle.loads(base64.b64decode(payload.encode("ascii"), validate=True))  # ruff: ignore[suspicious-pickle-usage]
    if not callable(getattr(formatter, "format", None)):
        message = "Serialized Litestar formatter does not provide format()"
        raise TypeError(message)
    return cast("_LogFormatter", formatter)


def _formatter_from_logger(logger: logging.Logger) -> _LogFormatter | None:
    current: logging.Logger | None = logger
    visited: set[int] = set()
    while current is not None and id(current) not in visited:
        visited.add(id(current))
        formatter = _formatter_from_handlers(current.handlers)
        if formatter is not None:
            return formatter
        if not current.propagate:
            return None
        current = current.parent
    return None


def _formatter_from_handlers(handlers: Iterable[object], visited: set[int] | None = None) -> _LogFormatter | None:
    seen = visited if visited is not None else set()
    for handler in handlers:
        if id(handler) in seen:
            continue
        seen.add(id(handler))
        formatter = getattr(handler, "formatter", None)
        if _is_formatter(formatter):
            return formatter
        listener = getattr(handler, "listener", None)
        nested_handlers = getattr(listener, "handlers", ()) if listener is not None else ()
        formatter = _formatter_from_handlers(_as_iterable(nested_handlers), seen)
        if formatter is not None:
            return formatter
        formatter = _formatter_from_handlers(_as_iterable(getattr(handler, "handlers", ())), seen)
        if formatter is not None:
            return formatter
    return None


def _formatter_from_config(logging_config: object | None) -> _LogFormatter | None:
    standard_config = getattr(logging_config, "standard_lib_logging_config", None)
    if standard_config is not None:
        logging_config = standard_config

    formatters = getattr(logging_config, "formatters", None)
    handlers = getattr(logging_config, "handlers", None)
    loggers = getattr(logging_config, "loggers", None)
    root = getattr(logging_config, "root", None)
    if not isinstance(formatters, Mapping) or not isinstance(handlers, Mapping):
        return None

    logger_config = loggers.get("litestar", {}) if isinstance(loggers, Mapping) else {}
    if not isinstance(logger_config, Mapping):
        logger_config = {}
    handler_names = _handler_names(logger_config.get("handlers"))
    if not handler_names and isinstance(root, Mapping):
        handler_names = _handler_names(root.get("handlers"))

    formatter_config = _formatter_config_from_handler_names(handler_names, handlers, formatters)
    if formatter_config is None:
        return None
    if _is_formatter(formatter_config):
        return cast("_LogFormatter", formatter_config)
    if not isinstance(formatter_config, Mapping):
        return None
    try:
        formatter = logging.config.DictConfigurator({"version": 1}).configure_formatter(
            deepcopy(dict(formatter_config))
        )
    except Exception as error:
        raise _setup_error(error) from error
    if not _is_formatter(formatter):
        raise _setup_error(TypeError("configured formatter does not provide format()"))
    return formatter


def _formatter_config_from_handler_names(
    handler_names: Sequence[str],
    handlers: Mapping[object, object],
    formatters: Mapping[object, object],
) -> object | None:
    pending = list(handler_names)
    visited: set[str] = set()
    while pending:
        handler_name = pending.pop(0)
        if handler_name in visited:
            continue
        visited.add(handler_name)
        handler = handlers.get(handler_name)
        if not isinstance(handler, Mapping):
            continue
        formatter_name = handler.get("formatter")
        if isinstance(formatter_name, str) and formatter_name in formatters:
            return formatters[formatter_name]
        pending.extend(_handler_names(handler.get("handlers")))
    return None


def _handler_names(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, (list, tuple)):
        return [item for item in value if isinstance(item, str)]
    return []


def _serialized_formatter(formatter: _LogFormatter) -> dict[str, str]:
    formatter_type = type(formatter)
    clone = formatter_type.__new__(formatter_type)
    state = getattr(formatter, "__dict__", None)

    if isinstance(state, dict):
        detached_state = state.copy()
        for key in ("processors", "foreign_pre_chain"):
            if key in detached_state and detached_state[key] is not None:
                detached_state[key] = list(detached_state[key])
        clone.__dict__.update(detached_state)

    for formatter_class in formatter_type.__mro__:
        for key, descriptor in vars(formatter_class).items():
            if not isinstance(descriptor, MemberDescriptorType):
                continue
            try:
                value = descriptor.__get__(formatter, formatter_type)
            except AttributeError:
                continue
            if key in {"processors", "foreign_pre_chain"} and value is not None:
                value = list(value)
            descriptor.__set__(clone, value)

    try:
        payload = base64.b64encode(pickle.dumps(clone, protocol=pickle.HIGHEST_PROTOCOL)).decode("ascii")
        load_serialized_formatter(payload)
    except Exception as error:
        raise _setup_error(error) from error
    return {
        "()": "litestar_granian.logging.load_serialized_formatter",
        "payload": payload,
    }


def _setup_error(error: Exception) -> _FormatterSetupError:
    return _FormatterSetupError(
        "Unable to reconstruct Litestar's active formatter for Granian. "
        "Provide a complete Granian logging configuration with --log-config. "
        f"Original error: {error}"
    )


def _is_formatter(value: object) -> bool:
    return callable(getattr(value, "format", None))


def _as_iterable(value: object) -> Iterable[object]:
    if isinstance(value, (str, bytes)) or value is None:
        return ()
    if isinstance(value, Iterable):
        return value
    return ()
